# Generated by Django 4.0.4 on 2022-07-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSesiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion_perfil',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
