# Generated by Django 4.0.4 on 2022-07-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSesiones', '0005_alter_sesion_perfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion_perfil',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sesion_perfil',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesion_perfil',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
