# Generated by Django 4.0.4 on 2022-06-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_receta', models.CharField(max_length=60)),
                ('ingredientes', models.CharField(max_length=300)),
                ('instrucciones', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=60)),
                ('imagen_de_comida', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
