# Generated by Django 4.0.4 on 2022-06-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFunciones', '0002_restaurantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantes',
            name='link_direccion',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantes',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantes',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
