# Generated by Django 4.0.4 on 2022-06-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFunciones', '0003_restaurantes_link_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantes',
            name='imagen',
            field=models.URLField(default="{% url '/static/assets/img/hansel-gretel.jpg' %}", max_length=300),
        ),
    ]
