# Generated by Django 4.0.4 on 2022-06-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFunciones', '0004_alter_restaurantes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantes',
            name='imagen',
            field=models.URLField(blank=True, default="{% url '/static/assets/img/hansel-gretel.jpg' %}", max_length=300, null=True),
        ),
    ]
