# Generated by Django 4.0.4 on 2022-06-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFunciones', '0005_alter_restaurantes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantes',
            name='imagen',
            field=models.URLField(blank=True, default='https://previews.123rf.com/images/blotty/blotty1707/blotty170700012/82776756-vector-vintage-burger-drawing-mano-dibuja-la-ilustraci%C3%B3n-de-comida-r%C3%A1pida-monocromo-.jpg', max_length=300, null=True),
        ),
    ]
