# Generated by Django 4.0.4 on 2022-06-27 23:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppFunciones', '0006_alter_restaurantes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantes',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurantes',
            name='link_direccion',
            field=models.URLField(blank=True, default='https://www.google.com.ar/maps', max_length=300, null=True),
        ),
    ]
