# Generated by Django 4.0.4 on 2022-06-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFunciones', '0007_alter_restaurantes_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantes',
            name='descripcion',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
