# Generated by Django 4.0.4 on 2022-07-04 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFunciones', '0008_restaurantes_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='ingredientes',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='instrucciones',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='restaurantes',
            name='descripcion',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('resto', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='AppFunciones.restaurantes')),
            ],
        ),
    ]
