# Generated by Django 4.0.4 on 2022-07-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFunciones', '0008_restaurantes_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
    ]
