# Generated by Django 4.0.4 on 2022-07-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFunciones', '0009_criticas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criticas',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
