# Generated by Django 4.0.4 on 2022-07-04 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFunciones', '0009_alter_recetas_ingredientes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='nombre',
            new_name='nombre_usuario',
        ),
    ]
