# Generated by Django 4.0.4 on 2022-07-03 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFunciones', '0010_rename_nombre_criticas_titulo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Criticas',
            new_name='Comentario',
        ),
    ]
