# Generated by Django 4.0.4 on 2022-07-04 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFunciones', '0011_alter_restaurantes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='resto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='AppFunciones.restaurantes'),
        ),
    ]
