# Generated by Django 4.0.4 on 2022-07-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFunciones', '0012_alter_comentario_resto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='imagen_de_comida',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
