# Generated by Django 4.0.4 on 2022-07-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFunciones', '0013_alter_recetas_imagen_de_comida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='instrucciones',
            field=models.TextField(max_length=1000),
        ),
    ]
