# Generated by Django 4.0.4 on 2022-07-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFunciones', '0014_alter_recetas_instrucciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantes',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
